spring.application.name=quantitymeasuementapp

spring.datasource.url=jdbc:mysql://localhost:3306/quantitymeasurement
spring.datasource.username=root
spring.datasource.password=Panditji@23

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.application.key=1f0511e309gebfvnjogehdfvnjksmlfgrjkhg3474f622d882763%^&*()*&&^&*(*&nkdnvnkn9896
spring.application.token.expiry=31536000